steps:

  - label: ":habicat: Promote Release to Stable"
    command: /bin/true
    skip: Not implemented yet
    agents:
      queue: habitat-release

  - wait

  - label: "Promote Bintray Releases"
    command: /bin/true
    skip: Not implemented yet
    agents:
      queue: habitat-release

  - label: ":mac: Promote Homebrew Release"
    command: /bin/true
    skip: Not implemented yet
    agents:
      queue: habitat-release

  - label: "Build Bootstrap Bundle and push to :s3:"
    command: /bin/true
    skip: Not implemented yet
    agents:
      queue: habitat-release

  - label: "Add core/backline to Acceptance Environment"
    command: /bin/true
    skip: Not implemented yet
    agents:
      queue: habitat-release

  - label: "Rebuild and promote the worker"
    command: /bin/true
    skip: Not implemented yet
    agents:
      queue: habitat-release

  - label: "Destroy Release Channel"
    command: .buildkite/scripts/destroy_release_channel.sh
    agents:
      queue: habitat-release

  - label: ":github: Publish Github Release"
    command: /bin/true
    skip: Not implemented yet
    agents:
      queue: habitat-release

  - label: "Update Documentation"
    command: /bin/true
    skip: Not implemented yet
    agents:
      queue: habitat-release
