# TODO (CM): To build from a tag, look at BUILDKITE_TAG
#            If there's something there, generate a channel and emit release steps;
#            Otherwise, do nothing (eventually, emit normal everyday CI steps)
#

# TODO Also need to wean off of TravisCI as we're doing this. We'll
# probably keep the Mac and Windows builds where they are for now, for
# instance.

steps:
  - label: ":habicat: core/hab"
    command: /bin/true
    # command: .buildkite/scripts/build-component.sh hab
    agents:
      queue: habitat-release

  - wait

  - label: ":habicat: :hammer_and_wrench: core/hab-plan-build"
    command: /bin/true
    agents:
      queue: habitat-release

  - wait

  - label: ":habicat: core/hab-backline"
    command: /bin/true
    agents:
      queue: habitat-release

  - label: ":habicat: core/hab-bintray-publish"
    command: /bin/true
    agents:
      queue: habitat-release

  - wait

  - label: ":habicat: core/hab-studio"
    command: /bin/true
    agents:
      queue: habitat-release

  - wait

  - label: ":habicat: core/hab-sup"
    command: /bin/true
    agents:
      queue: habitat-release

  - wait

  # Exporters

  - label: ":habicat: core/hab-pkg-aci Build"
    command: /bin/true
    agents:
      queue: habitat-release

  - label: ":cloudfoundry: core/hab-pkg-cfize Build"
    command: /bin/true
    agents:
      queue: habitat-release

  - label: ":docker: core/hab-pkg-export-docker Build"
    command: /bin/true
    agents:
      queue: habitat-release

  - label: ":k8s: core/hab-pkg-export-kubernetes Build"
    command: /bin/true
    agents:
      queue: habitat-release

  - label: ":helm: core/hab-pkg-export-helm Build"
    command: /bin/true
    agents:
      queue: habitat-release

  - label: ":habicat: core/hab-pkg-export-tar Build"
    command: /bin/true
    agents:
      queue: habitat-release

  - label: ":habicat: core/hab-pkg-mesosize Build"
    command: /bin/true
    agents:
      queue: habitat-release

  - block: "Promote launcher to release channel?"

  - block: ":shipit: Release (?)"
    prompt: "Is it good to release, or do we need to go back to the drawing board?"
    fields:
      - select: "Action"
        required: true
        key: "release-action"
        options:
          - label: "Release"
            value: "release"
          - label: "Abort"
            value: "abort"

  - label: ":pipeline:"
    command: .buildkite/finish_release.sh
