# TODO Also need to wean off of TravisCI as we're doing this. We'll
# probably keep the Mac and Windows builds where they are for now, for
# instance.

steps:
  - label: ":habicat: core/hab"
    command: .buildkite/scripts/build_component.sh hab
    agents:
      queue: habitat-release

  - wait

  - label: ":habicat: :hammer_and_wrench: core/hab-plan-build"
    command: .buildkite/scripts/build_component.sh plan-build
    agents:
      queue: habitat-release

  - wait

  - label: ":drum_with_drumsticks: :habicat: :drum_with_drumsticks: core/hab-backline"
    command: .buildkite/scripts/build_component.sh backline
    agents:
      queue: habitat-release

  - label: ":habicat: core/hab-bintray-publish"
    command: /bin/true
    agents:
      queue: habitat-release

  - wait

  - label: ":habicat: core/hab-studio"
    command: /bin/true
    agents:
      queue: habitat-release

  - wait

  - label: ":habicat: core/hab-sup"
    command: /bin/true
    agents:
      queue: habitat-release

  - wait

  # Exporters

  # TODO: Create an ACI emoji
  - label: ":habicat: core/hab-pkg-aci"
    command: /bin/true
    agents:
      queue: habitat-release

  - label: ":cloudfoundry: core/hab-pkg-cfize"
    command: /bin/true
    agents:
      queue: habitat-release

  - label: ":docker: core/hab-pkg-export-docker"
    command: /bin/true
    agents:
      queue: habitat-release

  - label: ":k8s: core/hab-pkg-export-kubernetes"
    command: /bin/true
    agents:
      queue: habitat-release

  - label: ":helm: core/hab-pkg-export-helm"
    command: /bin/true
    agents:
      queue: habitat-release

  - label: ":package: core/hab-pkg-export-tar"
    command: /bin/true
    agents:
      queue: habitat-release

  # TODO: Create a Mesos emoji
  - label: ":habicat: core/hab-pkg-mesosize"
    command: /bin/true
    agents:
      queue: habitat-release

  - block: ":thumbs_up: Promote Launcher to Release Channel?"

  - block: ":shipit: :question:"
    prompt: "Is it good to release, or do we need to go back to the drawing board?"
    fields:
      - select: "Action"
        required: true
        key: "release-action"
        options:
          - label: "Release"
            value: "release"
          - label: "Abort"
            value: "abort"

  - label: ":pipeline:"
    command: .buildkite/scripts/finish_release.sh
